### ISSUE TITLE
Error: Order is Not Open to Cancel - Aliceblue Error

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#19] opened 2024-05-08 06:02 UTC
No Pending Sell order in Orderbook for MKT Executed Order

 },
    {
        "channel": "Premium jackpot",
        "id": 1171514737428236,
        "symbol": "NFO:BANKNIFTY08MAY24C47400",
        "entry_range": "690",
        "target_range": "720.0|760.0|790.0|890.0|940.0",
        "sl": 650.0,
        "quantity": "15|15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-08 11:19:34",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "XXX",
        "price": 690.0,
        "ltp": 712.1,
        "pnl": 0,
        "entry": {
            "symbol": "BANKNIFTY08MAY24C47400",
            "quantity": 30,
            "side": "B",
            "price": "0.00",
            "trigger_price": "00.00",
            "average_price": "717.20",
            "filled_quantity": 30,
            "exchange": "NFO",
            "order_id": "24050800164037",
            "broker_timestamp": "08/05/2024 11:19:48",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "MKT",
            "Status": "complete"
        }
    },

![image](https://github.com/pannet1/telegram-trades/assets/168721095/1b3617c2-1e3e-4ee4-b9f7-583cfb95c90a)

**Comment by pannet1** [comment] 2024-05-08 06:26
duplicate of #16

**Closed by pannet1** 2024-05-08 06:26 UTC
